engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
      - php
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
      Design/TooManyFields:
        enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
